# Generated by Django 5.1.7 on 2025-07-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('distribution_center_id', models.IntegerField()),
            ],
        ),
    ]
